# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'binomialDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class binomialDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(969, 770)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 731, 741))
        self.groupBox.setObjectName("groupBox")
        self.label_n = QtWidgets.QLabel(Dialog)
        self.label_n.setGeometry(QtCore.QRect(760, 10, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_n.setFont(font)
        self.label_n.setObjectName("label_n")
        self.label_p = QtWidgets.QLabel(Dialog)
        self.label_p.setGeometry(QtCore.QRect(760, 50, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_p.setFont(font)
        self.label_p.setObjectName("label_p")
        self.lineEdit_n = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_n.setGeometry(QtCore.QRect(770, 20, 113, 21))
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.lineEdit_p = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_p.setGeometry(QtCore.QRect(770, 60, 113, 21))
        self.lineEdit_p.setObjectName("lineEdit_p")
        self.pushButton_drawing = QtWidgets.QPushButton(Dialog)
        self.pushButton_drawing.setGeometry(QtCore.QRect(860, 350, 88, 23))
        self.pushButton_drawing.setObjectName("pushButton_drawing")
        self.pushButton_clear = QtWidgets.QPushButton(Dialog)
        self.pushButton_clear.setGeometry(QtCore.QRect(860, 420, 88, 23))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.comboBox_style = QtWidgets.QComboBox(Dialog)
        self.comboBox_style.setGeometry(QtCore.QRect(790, 100, 51, 21))
        self.comboBox_style.setObjectName("comboBox_style")
        self.comboBox_style.addItem("")
        self.comboBox_style.addItem("")
        self.label_style = QtWidgets.QLabel(Dialog)
        self.label_style.setGeometry(QtCore.QRect(760, 100, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.label_style.setFont(font)
        self.label_style.setObjectName("label_style")
        self.label_mouseX = QtWidgets.QLabel(Dialog)
        self.label_mouseX.setGeometry(QtCore.QRect(460, 740, 71, 16))
        self.label_mouseX.setObjectName("label_mouseX")
        self.label_mouseY = QtWidgets.QLabel(Dialog)
        self.label_mouseY.setGeometry(QtCore.QRect(520, 740, 91, 20))
        self.label_mouseY.setObjectName("label_mouseY")
        self.pushButton_return = QtWidgets.QPushButton(Dialog)
        self.pushButton_return.setGeometry(QtCore.QRect(860, 490, 88, 23))
        self.pushButton_return.setObjectName("pushButton_return")
        self.comboBox_area = QtWidgets.QComboBox(Dialog)
        self.comboBox_area.setGeometry(QtCore.QRect(790, 150, 91, 21))
        self.comboBox_area.setObjectName("comboBox_area")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.label_area = QtWidgets.QLabel(Dialog)
        self.label_area.setGeometry(QtCore.QRect(760, 150, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.label_area.setFont(font)
        self.label_area.setObjectName("label_area")
        self.label_a = QtWidgets.QLabel(Dialog)
        self.label_a.setGeometry(QtCore.QRect(900, 10, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_a.setFont(font)
        self.label_a.setObjectName("label_a")
        self.label_b = QtWidgets.QLabel(Dialog)
        self.label_b.setGeometry(QtCore.QRect(900, 50, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_b.setFont(font)
        self.label_b.setObjectName("label_b")
        self.lineEdit_a = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_a.setGeometry(QtCore.QRect(910, 20, 41, 21))
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.lineEdit_b = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_b.setGeometry(QtCore.QRect(910, 60, 41, 21))
        self.lineEdit_b.setObjectName("lineEdit_b")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Graph"))
        self.label_n.setText(_translate("Dialog", "n"))
        self.label_p.setText(_translate("Dialog", "p"))
        self.pushButton_drawing.setText(_translate("Dialog", "Drawing"))
        self.pushButton_clear.setText(_translate("Dialog", "Clear"))
        self.comboBox_style.setItemText(0, _translate("Dialog", "pdf"))
        self.comboBox_style.setItemText(1, _translate("Dialog", "cdf"))
        self.label_style.setText(_translate("Dialog", "Style"))
        self.label_mouseX.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">X:</span></p></body></html>"))
        self.label_mouseY.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Y:</span></p></body></html>"))
        self.pushButton_return.setText(_translate("Dialog", "Return"))
        self.comboBox_area.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_area.setItemText(1, _translate("Dialog", "x<=a"))
        self.comboBox_area.setItemText(2, _translate("Dialog", "a<=x<=b"))
        self.comboBox_area.setItemText(3, _translate("Dialog", "x>=b"))
        self.label_area.setText(_translate("Dialog", "Area"))
        self.label_a.setText(_translate("Dialog", "a"))
        self.label_b.setText(_translate("Dialog", "b"))
