# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hypergeometricDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator, QDoubleValidator


class HypergeometricDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1093, 780)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(731, 741))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_M = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_M.setFont(font)
        self.label_M.setObjectName("label_M")
        self.horizontalLayout_2.addWidget(self.label_M)
        spacerItem = QtWidgets.QSpacerItem(13, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lineEdit_M = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_M.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_M.setObjectName("lineEdit_M")
        self.horizontalLayout_2.addWidget(self.lineEdit_M)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_N = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_N.setFont(font)
        self.label_N.setObjectName("label_N")
        self.horizontalLayout.addWidget(self.label_N)
        spacerItem2 = QtWidgets.QSpacerItem(13, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lineEdit_N = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_N.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_N.setObjectName("lineEdit_N")
        self.horizontalLayout.addWidget(self.lineEdit_N)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_n = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_n.setFont(font)
        self.label_n.setObjectName("label_n")
        self.horizontalLayout_3.addWidget(self.label_n)
        spacerItem4 = QtWidgets.QSpacerItem(13, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.lineEdit_n = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_n.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.horizontalLayout_3.addWidget(self.lineEdit_n)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_area_regel_2 = QtWidgets.QLabel(Dialog)
        self.label_area_regel_2.setLineWidth(1)
        self.label_area_regel_2.setObjectName("label_area_regel_2")
        self.horizontalLayout_4.addWidget(self.label_area_regel_2)
        spacerItem5 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_area_regel = QtWidgets.QLabel(Dialog)
        self.label_area_regel.setObjectName("label_area_regel")
        self.horizontalLayout_5.addWidget(self.label_area_regel)
        spacerItem9 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        spacerItem10 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_style = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.label_style.setFont(font)
        self.label_style.setObjectName("label_style")
        self.horizontalLayout_7.addWidget(self.label_style)
        spacerItem11 = QtWidgets.QSpacerItem(17, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.comboBox_style = QtWidgets.QComboBox(Dialog)
        self.comboBox_style.setObjectName("comboBox_style")
        self.comboBox_style.addItem("")
        self.comboBox_style.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_style)
        spacerItem12 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem13 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_area = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.label_area.setFont(font)
        self.label_area.setObjectName("label_area")
        self.horizontalLayout_8.addWidget(self.label_area)
        spacerItem14 = QtWidgets.QSpacerItem(17, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.comboBox_area = QtWidgets.QComboBox(Dialog)
        self.comboBox_area.setObjectName("comboBox_area")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_area)
        spacerItem15 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        spacerItem16 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem16)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_a = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_a.setFont(font)
        self.label_a.setObjectName("label_a")
        self.horizontalLayout_9.addWidget(self.label_a)
        spacerItem17 = QtWidgets.QSpacerItem(13, 21, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        self.lineEdit_a = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_a.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.horizontalLayout_9.addWidget(self.lineEdit_a)
        spacerItem18 = QtWidgets.QSpacerItem(17, 21, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem18)
        self.label_b = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_b.setFont(font)
        self.label_b.setObjectName("label_b")
        self.horizontalLayout_9.addWidget(self.label_b)
        spacerItem19 = QtWidgets.QSpacerItem(13, 21, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem19)
        self.lineEdit_b = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_b.setObjectName("lineEdit_b")
        self.horizontalLayout_9.addWidget(self.lineEdit_b)
        spacerItem20 = QtWidgets.QSpacerItem(13, 21, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem20)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        spacerItem21 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem21)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.label_area_result = QtWidgets.QLabel(Dialog)
        self.label_area_result.setText("")
        self.label_area_result.setObjectName("label_area_result")
        self.verticalLayout_9.addWidget(self.label_area_result)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        spacerItem22 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem22)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_point = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.label_point.setFont(font)
        self.label_point.setObjectName("label_point")
        self.horizontalLayout_10.addWidget(self.label_point)
        spacerItem23 = QtWidgets.QSpacerItem(13, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem23)
        self.lineEdit_point = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_point.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_point.setObjectName("lineEdit_point")
        self.horizontalLayout_10.addWidget(self.lineEdit_point)
        spacerItem24 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem24)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.verticalLayout_13.addLayout(self.verticalLayout_10)
        spacerItem25 = QtWidgets.QSpacerItem(17, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem25)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem26 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem26)
        self.pushButton_drawing = QtWidgets.QPushButton(Dialog)
        self.pushButton_drawing.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton_drawing.setObjectName("pushButton_drawing")
        self.horizontalLayout_11.addWidget(self.pushButton_drawing)
        spacerItem27 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem27)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem28)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem29 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem29)
        self.pushButton_clear = QtWidgets.QPushButton(Dialog)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_12.addWidget(self.pushButton_clear)
        spacerItem30 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem30)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem31)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem32 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem32)
        self.pushButton_return = QtWidgets.QPushButton(Dialog)
        self.pushButton_return.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButton_return.setObjectName("pushButton_return")
        self.horizontalLayout_13.addWidget(self.pushButton_return)
        spacerItem33 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem33)
        self.verticalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.gridLayout.addLayout(self.verticalLayout_13, 1, 2, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem34, 1, 0, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem35, 2, 1, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem36, 0, 1, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem37, 1, 3, 1, 1)

        nIntvalidator = QIntValidator(self)
        nIntvalidator.setRange(0, 99999)
        self.lineEdit_M.setValidator(nIntvalidator)
        self.lineEdit_N.setValidator(nIntvalidator)
        self.lineEdit_n.setValidator(nIntvalidator)
        self.lineEdit_point.setValidator(nIntvalidator)

        pDoublevalidator = QDoubleValidator(self)
        pDoublevalidator.setRange(-99999, 99999)
        pDoublevalidator.setNotation(QDoubleValidator.StandardNotation)
        pDoublevalidator.setDecimals(2)
        self.lineEdit_a.setValidator(pDoublevalidator)
        self.lineEdit_b.setValidator(pDoublevalidator)

        self.label_a.setHidden(True)
        self.label_b.setHidden(True)
        self.lineEdit_a.setHidden(True)
        self.lineEdit_b.setHidden(True)
        self.label_area.setHidden(True)
        self.comboBox_area.setHidden(True)
        self.label_point.setHidden(True)
        self.lineEdit_point.setHidden(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Graph"))
        self.label_M.setText(_translate("Dialog", "N"))
        self.label_N.setText(_translate("Dialog", "M"))
        self.label_n.setText(_translate("Dialog", "n"))
        self.label_area_regel_2.setText(_translate("Dialog", "n <= M <= N"))
        self.label_area_regel.setText(_translate("Dialog", "k={0,1,...,m},m=min{n,M}"))
        self.label_style.setText(_translate("Dialog", "Style"))
        self.comboBox_style.setItemText(0, _translate("Dialog", "pmf"))
        self.comboBox_style.setItemText(1, _translate("Dialog", "cdf"))
        self.label_area.setText(_translate("Dialog", "Area"))
        self.comboBox_area.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_area.setItemText(1, _translate("Dialog", "x=a"))
        self.comboBox_area.setItemText(2, _translate("Dialog", "x<=a"))
        self.comboBox_area.setItemText(3, _translate("Dialog", "a<=x<=b"))
        self.comboBox_area.setItemText(4, _translate("Dialog", "x>=b"))
        self.label_a.setText(_translate("Dialog", "a"))
        self.label_b.setText(_translate("Dialog", "b"))
        self.label_point.setText(_translate("Dialog", "Point"))
        self.pushButton_drawing.setText(_translate("Dialog", "Drawing"))
        self.pushButton_clear.setText(_translate("Dialog", " Clear "))
        self.pushButton_return.setText(_translate("Dialog", " Return"))
